---
title: "Project7_draft"
author: "GitIn"
date: "10/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Introduction
Organismal biologists have a tendency to, in great error, forgo including phylogenetic structure in their research analyses [@Freckleton2002].

### Methods

### Results

```{r echo=FALSE}
library(geiger)

## Loading required package: ape
m.phy <- read.tree("mammal.tree.pruned.txt")
m.phy$tip.label <- gsub("(\\w+)_(\\w+)","\\1 \\2",m.phy$tip.label)
m.phy0<- rescale(m.phy, model = "lambda", 0)
m.phy5 <- rescale(m.phy, model = "lambda", 0.5)
par(mfcol = c(1, 3))
plot(m.phy)
plot(m.phy5)
plot(m.phy0)

library(ape)
library(phytools)

## Loading required package: maps
sim.trait <- runif(Ntip(m.phy))
names(sim.trait) <- m.phy$tip.label
print(sim.trait)
sim.sig <- phylosig(m.phy,sim.trait,method="lambda",test=T)
print(sim.sig)

```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

## Discussion

## Author Contributions

## References